base mip
baobabsoluciones/flexible-vrp pull request #3
Opened 2023-02-17 13:36 UTC by alvaroelectronico

Moving MILP model into master branch

2023-02-17 14:03 UTC, ggsdc requested changes
Un simple comentario, dejad los ficheros excel fuera del repositorio, es mejor que no los subáis

2025-02-26 17:08 UTC, hugolarzabal commented
@alvaroelectronico can we close this PR?

2025-07-21 11:25 UTC, ggsdc commented
@alvaroelectronico @hugolarzabal @dlopbar one of you should take this PR, delete the excel files and then we can merge. Please add it to your TODO list, I do not care who

2025-07-28 08:01 UTC, ggsdc commented
@alvaroelectronico @dlopbar @hugolarzabal I'm going to close this PR for now due to the lack of activity. If any of you want to finish the work it can be reopenend

2025-07-28 08:01 UTC, closed without merging